# Generated by Django 3.2.12 on 2022-03-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teleuser',
            old_name='char_id',
            new_name='chat_id',
        ),
    ]
